[package]
name = "librespeed-rs"
version = "1.4.0"
edition = "2021"
authors = ["Sudo Dios"]
description = "Rust backend for LibreSpeed"

[features]
default = ["sqlite","mysql","postgres"]

sqlite = ["sqlx/sqlite"]
mysql = ["sqlx/mysql-rsa"]
postgres = ["sqlx/postgres"]

[dependencies]
#async net
tokio = {version = "1.53.1", features = ["net","io-util","rt","macros","rt-multi-thread","sync","signal","time"]}
tokio-rustls = {version = "0.26.4", features = ["tls12","ring"], default-features = false}
webpki-roots = "1.0.9"
rustls-pemfile = "2.2.0"
socket2 = "0.6.5"
listenfd = "1.0.2"
futures = "0.3.34"
dashmap = "7.0.0-rc2"
async-trait = "0.1.92"
#ip
maxminddb = "0.30.0"
#image processing
imageproc = "0.27.0"
ab_glyph = "0.2.32"
#serializer
serde_json = "1.0.151"
serde = { version = "1.0.229", features = ["derive"] }
#databases
uuid = { version = "1.24", features = ["v4"] }
chrono = "0.4.45"
sqlx = { version = "0.9.0",default-features = false, features = ["runtime-tokio","sqlite","mysql-rsa","postgres"], optional = true }
#conf
clap = { version = "4.6.6",features = ["std","color","help","usage"],default-features = false }
toml = "1.1.2"
#web
sha2 = "0.11.0"
handlebars = "6.4.4"
#logging
env_logger = { version = "0.11.11",default-features = false,features = ["auto-color","humantime"] }
log = "0.4.33"
indicatif = "0.18.6"
#assets
include_dir = "0.7.4"
case_insensitive_hashmap = "1.0.1"

[package.metadata.deb]
maintainer-scripts = "setup/debian/scripts/"
systemd-units = { enable = false }
revision = ""
assets = [
    ["target/release/librespeed-rs","/usr/bin/librespeed-rs","755"],
    ["assets/*","/var/lib/librespeed-rs/assets","644"],
    ["configs.toml","/var/lib/librespeed-rs/configs.toml","644"],
    ["country_asn.mmdb","/var/lib/librespeed-rs/country_asn.mmdb","644"],
    ["setup/debian/speedtest_rs.service","/lib/systemd/system/speedtest_rs.service","644"],
    ["setup/debian/speedtest_rs.socket","/lib/systemd/system/speedtest_rs.socket","644"]
]

[profile.release]
codegen-units = 1
opt-level = "z"
panic = "abort"
lto = true
strip = true
